version: '3.8'

services:
  mptcp-router:
    build: .
    container_name: mptcp-router
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /etc/netplan:/etc/netplan
      - /sys/class/net:/sys/class/net:ro
      - ./config/mptcp:/etc/mptcp
      - /lib/modules:/lib/modules:ro
    environment:
      - LAN_INTERFACE=${LAN_GATE_INTERFACE}
    restart: unless-stopped

  # FIXME:
  # firewall:
  #   image: registry.docker-cn.com/library/ubuntu:20.04
  #   container_name: mptcp-firewall
  #   network_mode: host
  #   volumes:
  #     - ./config/firewall:/etc/iptables
  #   command: ["sh", "-c", "apt-get update && apt-get install -y iptables && iptables-restore < /etc/iptables/rules.v4 && sleep infinity"]
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped
