version: '3.8'

services:
  optimizer:
    build: .
    container_name: netplan-optimizer
    restart: unless-stopped
    privileged: true      # Required for network access
    network_mode: host    # Needs direct host network access
    volumes:
      - ./config/netplan:/etc/netplan
      - /var/lib/netplan_optimizer:/var/lib/netplan_optimizer
      - /var/log:/var/log
      - /sys/class/net:/sys/class/net:ro
      - /proc/net/dev:/proc/net/dev:ro
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  notifier:
    image: alpine/socat
    command: "TCP-LISTEN:5000,fork EXEC:'/bin/cat'"
    ports:
      - "5000:5000"
    restart: unless-stopped

  cron:
    image: alpine
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "echo '*/30 * * * * /scripts/run_benchmark.sh' > /etc/crontabs/root
      && crond -f"