version: '3.8'

networks:
  default:
    driver: bridge
    enable_ip_masquerade: false

services:
  mptcp-router:
    build: .
    container_name: mptcp-router
    privileged: true
    network_mode: host
    volumes:
      - /etc/netplan:/etc/netplan
      - /sys/class/net:/sys/class/net:ro
      - ./config/mptcp:/etc/mptcp
    environment:
      - LAN_INTERFACE=${LAN_GATE_INTERFACE}
    restart: unless-stopped

  # FIXME:
  # firewall:
  #   image: ubuntu:20.04
  #   container_name: mptcp-firewall
  #   network_mode: host
  #   volumes:
  #     - ./config/firewall:/etc/iptables
  #   command: ["sh", "-c", "apt-get update && apt-get install -y iptables && iptables-restore < /etc/iptables/rules.v4 && sleep infinity"]
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped
