email:
  enabled: true
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: your_email@gmail.com
  password: your_app_password
  from_addr: your_email@gmail.com
  to_addrs: admin@yourdomain.com

sms:
  enabled: false
  twilio_account_sid: YOUR_TWILIO_SID
  twilio_auth_token: YOUR_TWILIO_TOKEN
  twilio_number: "+1234567890"
  to_numbers: "+15551234567"

slack:
  enabled: false
  webhook_url: YOUR_SLACK_WEBHOOK
  channel: "#network-alerts"